//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationSPPP.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lien
    {
        public long ID { get; set; }
        public long FID_Logigram { get; set; }
        public long FID_Document { get; set; }
        public int X1 { get; set; }
        public int Y1 { get; set; }
        public int X2 { get; set; }
        public int Y2 { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Logigram Logigram { get; set; }
    }
}
