//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationSPPP.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logigram : Document
    {
        public Logigram()
        {
            this.Liens = new HashSet<Lien>();
        }
    
        public Nullable<long> FID_Next { get; set; }
    
        public virtual ICollection<Lien> Liens { get; set; }
        public virtual Logigram Next { get; set; }
    }
}
